
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  install:
    docker:
      - image: circleci/node:12
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm 


  build:
    executor: node/default
    steps: 
      - checkout
      - node/install-packages: 
          pkg-manager: npm
      - run: 
          name: npm Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
      
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"

workflows:
  my_workflow:
    jobs:
      - install
      - build
      